# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatGui2.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 632)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 891, 561))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.groupBox = QtWidgets.QGroupBox(self.page_1)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 871, 521))
        self.groupBox.setObjectName("groupBox")
        
        self.p = QtGui.QPalette(self.palette())
        self.p.setColor(QtGui.QPalette.Highlight, QtGui.QColor(QtCore.Qt.darkGreen))
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_3.setGeometry(QtCore.QRect(590, 30, 81, 141))
        self.progressBar_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_3.setAutoFillBackground(False)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setPalette(self.p)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setGeometry(QtCore.QRect(290, 30, 81, 141))
        self.progressBar_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_2.setAutoFillBackground(False)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setPalette(self.p)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 30, 81, 141))
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setPalette(self.p)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_4 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 190, 81, 141))
        self.progressBar_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_4.setAutoFillBackground(False)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setPalette(self.p)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_5.setEnabled(True)
        self.progressBar_5.setGeometry(QtCore.QRect(290, 190, 81, 141))
        self.progressBar_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_5.setAutoFillBackground(False)
        self.progressBar_5.setMinimum(0)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setPalette(self.p)
        self.progressBar_5.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setInvertedAppearance(False)
        self.progressBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_6.setGeometry(QtCore.QRect(590, 190, 81, 141))
        self.progressBar_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_6.setAutoFillBackground(False)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setPalette(self.p)
        self.progressBar_6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_6.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_7.setGeometry(QtCore.QRect(10, 350, 81, 141))
        self.progressBar_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_7.setAutoFillBackground(False)
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setPalette(self.p)
        self.progressBar_7.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_7.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_7.setObjectName("progressBar_7")
        self.progressBar_8 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_8.setGeometry(QtCore.QRect(290, 350, 81, 141))
        self.progressBar_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_8.setAutoFillBackground(False)
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setPalette(self.p)
        self.progressBar_8.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_8.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_8.setObjectName("progressBar_8")
        self.progressBar_9 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_9.setGeometry(QtCore.QRect(590, 350, 81, 141))
        self.progressBar_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_9.setAutoFillBackground(False)
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setPalette(self.p)
        self.progressBar_9.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_9.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_9.setObjectName("progressBar_9")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(250, 20, 20, 511))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_8.setGeometry(QtCore.QRect(100, 350, 140, 121))
        self.groupBox_8.setObjectName("groupBox_8")
        self.voltage_7 = QtWidgets.QLabel(self.groupBox_8)
        self.voltage_7.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_7.setObjectName("voltage_7")
        self.label_59 = QtWidgets.QLabel(self.groupBox_8)
        self.label_59.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.groupBox_8)
        self.label_60.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_60.setObjectName("label_60")
        self.temp_7 = QtWidgets.QLabel(self.groupBox_8)
        self.temp_7.setGeometry(QtCore.QRect(10, 90, 51, 17))
        self.temp_7.setObjectName("temp_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(110, 190, 140, 121))
        self.groupBox_5.setObjectName("groupBox_5")
        self.voltage_4 = QtWidgets.QLabel(self.groupBox_5)
        self.voltage_4.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_4.setObjectName("voltage_4")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_21.setObjectName("label_21")
        self.temp_4 = QtWidgets.QLabel(self.groupBox_5)
        self.temp_4.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_4.setObjectName("temp_4")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(110, 30, 140, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_12.setObjectName("label_12")
        self.voltage_1 = QtWidgets.QLabel(self.groupBox_2)
        self.voltage_1.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_1.setObjectName("voltage_1")
        self.temp_1 = QtWidgets.QLabel(self.groupBox_2)
        self.temp_1.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_1.setObjectName("temp_1")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(690, 30, 140, 121))
        self.groupBox_4.setObjectName("groupBox_4")
        self.voltage_3 = QtWidgets.QLabel(self.groupBox_4)
        self.voltage_3.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_3.setObjectName("voltage_3")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_18.setObjectName("label_18")
        self.temp_3 = QtWidgets.QLabel(self.groupBox_4)
        self.temp_3.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_3.setObjectName("temp_3")
        self.groupBox_10 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_10.setGeometry(QtCore.QRect(690, 350, 140, 121))
        self.groupBox_10.setObjectName("groupBox_10")
        self.voltage_9 = QtWidgets.QLabel(self.groupBox_10)
        self.voltage_9.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_9.setObjectName("voltage_9")
        self.label_65 = QtWidgets.QLabel(self.groupBox_10)
        self.label_65.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_10)
        self.label_66.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_66.setObjectName("label_66")
        self.temp_9 = QtWidgets.QLabel(self.groupBox_10)
        self.temp_9.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_9.setObjectName("temp_9")
        self.groupBox_9 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_9.setGeometry(QtCore.QRect(400, 350, 140, 121))
        self.groupBox_9.setObjectName("groupBox_9")
        self.voltage_8 = QtWidgets.QLabel(self.groupBox_9)
        self.voltage_8.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_8.setObjectName("voltage_8")
        self.label_62 = QtWidgets.QLabel(self.groupBox_9)
        self.label_62.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.groupBox_9)
        self.label_63.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_63.setObjectName("label_63")
        self.temp_8 = QtWidgets.QLabel(self.groupBox_9)
        self.temp_8.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_8.setObjectName("temp_8")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_7.setGeometry(QtCore.QRect(690, 190, 140, 121))
        self.groupBox_7.setObjectName("groupBox_7")
        self.voltage_6 = QtWidgets.QLabel(self.groupBox_7)
        self.voltage_6.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_6.setObjectName("voltage_6")
        self.label_26 = QtWidgets.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_7)
        self.label_27.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_27.setObjectName("label_27")
        self.temp_6 = QtWidgets.QLabel(self.groupBox_7)
        self.temp_6.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_6.setObjectName("temp_6")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(390, 30, 140, 121))
        self.groupBox_3.setObjectName("groupBox_3")
        self.voltage_2 = QtWidgets.QLabel(self.groupBox_3)
        self.voltage_2.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_2.setObjectName("voltage_2")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_15.setObjectName("label_15")
        self.temp_2 = QtWidgets.QLabel(self.groupBox_3)
        self.temp_2.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_2.setObjectName("temp_2")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_6.setGeometry(QtCore.QRect(400, 190, 140, 121))
        self.groupBox_6.setObjectName("groupBox_6")
        self.voltage_5 = QtWidgets.QLabel(self.groupBox_6)
        self.voltage_5.setGeometry(QtCore.QRect(10, 50, 41, 17))
        self.voltage_5.setObjectName("voltage_5")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(10, 70, 111, 17))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(10, 30, 67, 17))
        self.label_24.setObjectName("label_24")
        self.temp_5 = QtWidgets.QLabel(self.groupBox_6)
        self.temp_5.setGeometry(QtCore.QRect(10, 90, 71, 17))
        self.temp_5.setObjectName("temp_5")
        self.line_2 = QtWidgets.QFrame(self.groupBox)
        self.line_2.setGeometry(QtCore.QRect(560, 20, 20, 511))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.pushButton = QtWidgets.QPushButton(self.page_1)
        self.pushButton.setGeometry(QtCore.QRect(790, 530, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.dial = QtWidgets.QDial(self.page_1)
        self.dial.setGeometry(QtCore.QRect(730, 500, 50, 64))
        self.dial.setObjectName("dial")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(790, 530, 99, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        #MainWindow.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 25))
        #self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        #self.statusbar = QtWidgets.QStatusBar(MainWindow)
        #self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "BAttery Status"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Battery 7"))
        self.voltage_7.setText(_translate("MainWindow", "0 V"))
        self.label_59.setText(_translate("MainWindow", "Temperature  :"))
        self.label_60.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_7.setText(_translate("MainWindow", "0 "))
        self.groupBox_5.setTitle(_translate("MainWindow", "Battery 4"))
        self.voltage_4.setText(_translate("MainWindow", "0 V"))
        self.label_20.setText(_translate("MainWindow", "Temperature  :"))
        self.label_21.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_4.setText(_translate("MainWindow", "0 "))
        self.groupBox_2.setTitle(_translate("MainWindow", "Battery 1"))
        self.label_10.setText(_translate("MainWindow", "Voltage  :"))
        self.label_12.setText(_translate("MainWindow", "Temperature  :"))
        self.voltage_1.setText(_translate("MainWindow", "0 V"))
        self.temp_1.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Battery 3"))
        self.voltage_3.setText(_translate("MainWindow", "0 V"))
        self.label_17.setText(_translate("MainWindow", "Temperature  :"))
        self.label_18.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_3.setText(_translate("MainWindow", "0 "))
        self.groupBox_10.setTitle(_translate("MainWindow", "Battery 9"))
        self.voltage_9.setText(_translate("MainWindow", "0 V"))
        self.label_65.setText(_translate("MainWindow", "Temperature  :"))
        self.label_66.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_9.setText(_translate("MainWindow", "0 "))
        self.groupBox_9.setTitle(_translate("MainWindow", "Battery 8"))
        self.voltage_8.setText(_translate("MainWindow", "0 V"))
        self.label_62.setText(_translate("MainWindow", "Temperature  :"))
        self.label_63.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_8.setText(_translate("MainWindow", "0 "))
        self.groupBox_7.setTitle(_translate("MainWindow", "Battery 6"))
        self.voltage_6.setText(_translate("MainWindow", "0 V"))
        self.label_26.setText(_translate("MainWindow", "Temperature  :"))
        self.label_27.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_6.setText(_translate("MainWindow", "0 "))
        self.groupBox_3.setTitle(_translate("MainWindow", "Battery 2"))
        self.voltage_2.setText(_translate("MainWindow", "0 V"))
        self.label_14.setText(_translate("MainWindow", "Temperature  :"))
        self.label_15.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_2.setText(_translate("MainWindow", "0 "))
        self.groupBox_6.setTitle(_translate("MainWindow", "Battery 5"))
        self.voltage_5.setText(_translate("MainWindow", "0 V"))
        self.label_23.setText(_translate("MainWindow", "Temperature  :"))
        self.label_24.setText(_translate("MainWindow", "Voltage  :"))
        self.temp_5.setText(_translate("MainWindow", "0 "))
        self.pushButton.setText(_translate("MainWindow", "Detail"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
