# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BatGui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 526)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 791, 471))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.groupBox_5 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_5.setGeometry(QtCore.QRect(360, 110, 120, 80))
        self.groupBox_5.setObjectName("groupBox_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_3.setGeometry(QtCore.QRect(500, 10, 120, 80))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_9.setGeometry(QtCore.QRect(490, 230, 120, 80))
        self.groupBox_9.setObjectName("groupBox_9")
        self.line = QtWidgets.QFrame(self.page_1)
        self.line.setGeometry(QtCore.QRect(340, 10, 20, 431))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox = QtWidgets.QGroupBox(self.page_1)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 341, 461))
        self.groupBox.setObjectName("groupBox")
        
        self.p = QtGui.QPalette(self.palette())
        self.p.setColor(QtGui.QPalette.Highlight, QtGui.QColor(QtCore.Qt.darkGreen))
        
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_3.setGeometry(QtCore.QRect(10, 40, 61, 111))
        self.progressBar_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_3.setAutoFillBackground(False)
        self.progressBar_3.setProperty("value", 24)
        self.progressBar_3.setPalette(self.p)
        self.progressBar_3.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_3.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_3.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_2.setGeometry(QtCore.QRect(130, 40, 61, 111))
        self.progressBar_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_2.setAutoFillBackground(False)
        self.progressBar_2.setProperty("value", 24)
        self.progressBar_2.setPalette(self.p)
        self.progressBar_2.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(250, 40, 61, 111))
        self.progressBar.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setPalette(self.p)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Vertical)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar.setObjectName("progressBar")
        self.progressBar_4 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 180, 61, 111))
        self.progressBar_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_4.setAutoFillBackground(False)
        self.progressBar_4.setProperty("value", 24)
        self.progressBar_4.setPalette(self.p)
        self.progressBar_4.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_5.setEnabled(True)
        self.progressBar_5.setGeometry(QtCore.QRect(130, 180, 61, 111))
        self.progressBar_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_5.setAutoFillBackground(False)
        self.progressBar_5.setMinimum(0)
        self.progressBar_5.setProperty("value", 24)
        self.progressBar_5.setPalette(self.p)
        self.progressBar_5.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_5.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_5.setInvertedAppearance(False)
        self.progressBar_5.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_6.setGeometry(QtCore.QRect(250, 180, 61, 111))
        self.progressBar_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_6.setAutoFillBackground(False)
        self.progressBar_6.setProperty("value", 24)
        self.progressBar_6.setPalette(self.p)
        self.progressBar_6.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_6.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_6.setObjectName("progressBar_6")
        self.progressBar_7 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_7.setGeometry(QtCore.QRect(10, 320, 61, 111))
        self.progressBar_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_7.setAutoFillBackground(False)
        self.progressBar_7.setProperty("value", 24)
        self.progressBar_7.setPalette(self.p)
        self.progressBar_7.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_7.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_7.setObjectName("progressBar_7")
        self.progressBar_8 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_8.setGeometry(QtCore.QRect(130, 320, 61, 111))
        self.progressBar_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_8.setAutoFillBackground(False)
        self.progressBar_8.setProperty("value", 24)
        self.progressBar_8.setPalette(self.p)
        self.progressBar_8.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_8.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_8.setObjectName("progressBar_8")
        self.progressBar_9 = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_9.setGeometry(QtCore.QRect(250, 320, 61, 111))
        self.progressBar_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar_9.setAutoFillBackground(False)
        self.progressBar_9.setProperty("value", 24)
        self.progressBar_9.setPalette(self.p)
        self.progressBar_9.setOrientation(QtCore.Qt.Vertical)
        self.progressBar_9.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_9.setObjectName("progressBar_9")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 150, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(130, 150, 67, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(250, 150, 67, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 290, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(130, 290, 67, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(250, 290, 67, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 430, 67, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(130, 430, 67, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(250, 430, 67, 17))
        self.label_9.setObjectName("label_9")
        self.groupBox_6 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_6.setGeometry(QtCore.QRect(500, 110, 120, 80))
        self.groupBox_6.setObjectName("groupBox_6")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_7.setGeometry(QtCore.QRect(630, 110, 120, 80))
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_10.setGeometry(QtCore.QRect(630, 230, 120, 80))
        self.groupBox_10.setObjectName("groupBox_10")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_8.setGeometry(QtCore.QRect(360, 230, 120, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_2.setGeometry(QtCore.QRect(360, 10, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.page_1)
        self.groupBox_4.setGeometry(QtCore.QRect(630, 10, 120, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.dial = QtWidgets.QDial(self.page_1)
        self.dial.setGeometry(QtCore.QRect(390, 310, 50, 64))
        self.dial.setObjectName("dial")
        self.pushButton = QtWidgets.QPushButton(self.page_1)
        self.pushButton.setGeometry(QtCore.QRect(670, 400, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(670, 400, 99, 27))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        #MainWindow.setCentralWidget(self.centralwidget)
        #self.menubar = QtWidgets.QMenuBar(MainWindow)
        #self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        #self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        #self.statusbar = QtWidgets.QStatusBar(MainWindow)
        #self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Battery 4"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Battery 2"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Battery 8"))
        self.groupBox.setTitle(_translate("MainWindow", "BAttery Status"))
        self.label.setText(_translate("MainWindow", "Battery 1"))
        self.label_2.setText(_translate("MainWindow", "Battery 2"))
        self.label_3.setText(_translate("MainWindow", "Battery 3"))
        self.label_4.setText(_translate("MainWindow", "Battery 4"))
        self.label_5.setText(_translate("MainWindow", "Battery 5"))
        self.label_6.setText(_translate("MainWindow", "Battery 6"))
        self.label_7.setText(_translate("MainWindow", "Battery 7"))
        self.label_8.setText(_translate("MainWindow", "Battery 8"))
        self.label_9.setText(_translate("MainWindow", "Battery 9"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Battery 5"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Battery 6"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Battery 9"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Battery 7"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Battery 1"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Battery 3"))
        self.pushButton.setText(_translate("MainWindow", "Detail"))
        self.pushButton_2.setText(_translate("MainWindow", "Back"))
    
    def _trigger_refresh(self):
        self.update()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
